image: node:12.18.3


stages:
  - deploy


before_script:
  - npm install -g @angular/cli

pages:
  cache:
    paths:
      - client/node_modules/
  stage: deploy
  script:
    - npm ci
    - ng build --prod --base-href="https://geo-spatia.gitlab.io/geo-spatia/"
    - rm -rf public
    - mkdir public
    - mv dist/geo-spatia/* public/
  artifacts:
    paths:
      - public
  only:
    - main
